# Generated by Django 4.1.7 on 2023-03-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=300)),
                ('sector', models.CharField(max_length=200)),
                ('fundator', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rut', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
